### ISSUE TITLE
Error: Unknown encoding: 5406

### ISSUE THREAD

**Issue by yarax** [patriksimek/vm2#15]
Guys, lib doesn't work with node >= 4.0

```
> nvm use 4.0
> npm test
> /Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/mocha/lib/reporters/base.js:168
      , stack = err.stack || message
                   ^

Error: Unknown encoding: 5406
  at assertEncoding (fs.js:88:11)
  at Object.fs.readSync (fs.js:594:5)
  at Object.fs.readSync (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/polyfills.js:218:23)
  at Object.fs.readFileSync (fs.js:433:24)
  at Object.exports._compileFile (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/coffee-script/lib/coffee-script/coffee-script.js:224:14)
  at getSourceMap (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:22)
  at getSourceMapping (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/coffee-script/lib/coffee-script/coffee-script.js:351:19)
  at formatSourcePosition (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/coffee-script/lib/coffee-script/coffee-script.js:303:16)
  at /Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/coffee-script/lib/coffee-script/coffee-script.js:369:33
  at Function.Error.prepareStackTrace (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/coffee-script/lib/coffee-script/coffee-script.js:372:7)
  at /Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/mocha/lib/reporters/base.js:168:20
  at Array.forEach (native)
  at Function.exports.list (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/mocha/lib/reporters/base.js:159:12)
  at Spec.Base.epilogue (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/mocha/lib/reporters/base.js:312:10)
  at emitNone (events.js:72:20)
  at Runner.emit (events.js:166:7)
  at Runner.uncaught (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/mocha/lib/runner.js:563:8)
  at process.uncaught (/Users/Shopgate/shopgate/fcs-worker/node_modules/vm2/node_modules/mocha/lib/runner.js:580:10)
  at emitOne (events.js:77:13)
  at process.emit (events.js:169:7)
  at process._fatalException (node.js:211:26)

npm ERR! Test failed.  See above for more details.
```

Switching to 0.12 makes everything ok

**Comment by patriksimek** [comment]
Could you please test your code with latest version 0.2.4?
