### ISSUE TITLE
Hide information from stacktrace?

### ISSUE THREAD

**Issue by yhpark** [patriksimek/vm2#173]
Hi, I'm running a small service where 3rd party can run their js script in our sandbox. Also I'm letting the 3rd party devs to see stdout from the vm execution because otherwise it'd be really hard for them to debug their code.

However, I'm worried that the full path of the vm2 lib and other lower-level stacktrace information are shown in the error stacktrace thrown inside the vm, exposing directory structure, project name and etc. which might be used by hackers.

```js
new VM({sandbox: {console}})
  .run('try { throw new Error(); } catch (e) { console.log(e.stack) }')
```

console output:
```
Error
    at vm.js:1:13
    at Script.runInContext (vm.js:107:20)
    at VM.run (/...project path.../node_modules/vm2/lib/main.js:204:72)
    at repl:1:30
    at Script.runInThisContext (vm.js:96:20)
    at REPLServer.defaultEval (repl.js:329:29)
    at bound (domain.js:396:14)
    at REPLServer.runBound [as eval] (domain.js:409:12)
    at REPLServer.onLine (repl.js:627:10)
    at REPLServer.emit (events.js:187:15)
```

Is there any way to prevent this? thanks in advance.

**Comment by j-gurda** [comment]
What I would suggest to look into is to override `Error.prepareStackTrace` behavior. See https://v8.dev/docs/stack-trace-api
Of course some user code may override it to print whole stack trace but it may be good start. I gave up using VM2 and using standard VM module and my code looks as follows:

```javascript
function userCodeStackSanitizer(error, structuredStackTrace) {
    let originalStack = error.stack;
    let stackLines = originalStack.split('\n');
    let sanitized = [];
    for (let line of stackLines) {
        if (line.includes('at ContextifyScript.Script.runInContext (vm.js:') ||
            line.includes('at createScript (vm.js') {
            break;
        }
        sanitized.push(line);
    }
    error.stack = sanitized.join('\n');
}

let sandbox = {
    prepareStackTrace: userCodeStackSanitizer
};
let context = vm.createContext(sandbox);
vm.runInContext('Error.prepareStackTrace = prepareStackTrace;', context);
delete context.prepareStackTrace; //deleting prepareStackTrace to not be visible in globals
vm.runInContext('try { throw new Error(); } catch (e) { console.log(e.stack) }', context);
```

This is naive implementation but came to conclusion (which I strongly believe is valid) that if someone really wants to escape VM/VM2 it will do that anyway so securing other tenants should not be done on code level but on virtualization/infrastructure level. Hope that helps.
