### ISSUE TITLE
RegExp interpreted as [object Object] within NodeVM context

### ISSUE THREAD

**Issue by dylburger** [patriksimek/vm2#193]
Hi,

First, very much appreciate the work y'all have put into `vm2`. It's been incredibly helpful on a recent project. I'm also very new to `vm2` so I apologize if this question isn't articulate enough - happy to clarify.

I've produced a test case of the issue I discuss below [here](https://github.com/dylburger/vm2-jest-test/blob/master/jest-vm2.js).

I'm using the `expect` package from Facebook's jest library to test assertions within a `NodeVM` sandbox, specifically the `StringMatching` class (docs [here](https://jestjs.io/docs/en/expect#expectstringmatchingstring-regexp), code [here](https://github.com/facebook/jest/blob/665a93eec70c4f2d7809d1848fbc8ca60cfd8361/packages/expect/src/asymmetricMatchers.js#L228)). When I run the code in my test repo:

```bash
node jest-vm2.js
```

the following exception is raised:

```
/Users/dylan/pipedream/vm2-jest-test/node_modules/vm2/lib/main.js:430
                        throw this._internal.Decontextify.value(e);
                        ^

Error: Expected is not a String or a RegExp
    at new StringMatching (/Users/dylan/pipedream/vm2-jest-test/node_modules/expect/build/asymmetricMatchers.js:228:13)
    at Function.stringMatching (/Users/dylan/pipedream/vm2-jest-test/node_modules/expect/build/asymmetricMatchers.js:282:36)
    at Object.base.apply (/Users/dylan/pipedream/vm2-jest-test/node_modules/vm2/lib/contextify.js:439:32)
    at Object.<anonymous> (/Users/dylan/pipedream/vm2-jest-test/index.js:8:19)
    at NodeVM.run (/Users/dylan/pipedream/vm2-jest-test/node_modules/vm2/lib/main.js:428:23)
    at Object.<anonymous> (/Users/dylan/pipedream/vm2-jest-test/jest-vm2.js:11:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

The code works fine - that is, the assertion is met - outside of the sandbox, running Node `v8.10.0`.

I've narrowed the issue down to the [`isA` function](https://github.com/facebook/jest/blob/665a93eec70c4f2d7809d1848fbc8ca60cfd8361/packages/expect/src/jasmineUtils.js#L250) that the `StringMatching ` class uses internally:

``` javascript
export function isA(typeName: string, value: any) {
  return Object.prototype.toString.apply(value) === '[object ' + typeName + ']';
}
```

Normally, when a `RegExp` is passed to this function like I'm doing in my test, `Object.prototype.toString.apply(value)` should return `[object RegExp]`. But within the `vm2` sandbox, it returns `[object Object]`, which triggers the "Expected is not a String or a RegExp" error from the `StringMatching` constructor.

Let me know if this is expected and simply requires a change to `NodeVM` options, etc. Thanks!

**Comment by dylburger** [comment]
Hi y'all, so sorry to bug, I just wanted to raise this again and see if there's anything I'm doing wrong on my end, or if there's any more information you need to confirm the issue.

Thanks!

**Comment by patriksimek** [comment]
I can confirm that. Here's the minimal code to reproduce:

```javascript
const vm = new VM();

console.log(vm.run(`/x/ instanceof RegExp`)); // true
console.log(vm.run(`/x/.constructor === RegExp`)); // true 
console.log(Object.prototype.toString.call(vm.run(`/x/`))); // [object Object]
console.log(Object.prototype.toString.call(/x/)); // [object RegExp]
```

I'm not aware of how `toString` works internally so I'm not even sure if that can be fixed. I can't spend any time investigating atm so any help is appreciated.

**Comment by Y-qwq** [comment]
> This seems to be fixed by [fe90a04](https://github.com/patriksimek/vm2/commit/fe90a042f3955cba4291f76481caa213a1d46e68).

This problem seems to have reappeared again, but for the `process`.

Here's the minimal code to reproduce:

```js
const { NodeVM } = require('vm2')
const vm = vm = new NodeVM()
Object.prototype.toString.call(vm.run('process')) // [object Object]
vm.run(`console.log(Object.prototype.toString.call(process) === "[object Object]")`) // true
Object.prototype.toString.call(process) // [object process]
```

**Comment by XmiliaH** [comment]
First, `vm.run('process')` will return the export object, not the process object.
Second, the native process has the `Symbol.toStringTag` set to `"process"`. We currently do not do this as making an exact copy of the process object is hard.

**Comment by Y-qwq** [comment]
> First, `vm.run('process')` will return the export object, not the process object.
> Second, the native process has the `Symbol.toStringTag` set to `"process"`. We currently do not do this as making an exact copy of the process object is hard.

Okay, thanks for your answer.
