### ISSUE TITLE
`require('events')` results in `Error: Cannot find module 'internal/errors'`

### ISSUE THREAD

**Issue by kimamula** [patriksimek/vm2#202]
Node.js: v11.14.0
vm2: v3.6.11

```sh
$ node
> const { NodeVM } = require('vm2');
undefined
> const vm = new NodeVM({ require: { builtin: ['events'] } });
undefined
> vm.run(`require('events')`);
Thrown:
{ Error: Cannot find module 'internal/errors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at Object.require (internal/modules/cjs/helpers.js:14:16)
    at _requireBuiltin (/path/to/my-project/node_modules/vm2/lib/sandbox.js:172:35)
    at events.vm.js:30:5
    at _requireBuiltin (/path/to/my-project/node_modules/vm2/lib/sandbox.js:164:32)
    at _require (/path/to/my-project/node_modules/vm2/lib/sandbox.js:213:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by kimamula** [comment]
As of Node.js v12.0.0 and vm2 v3.8.0, the same code throws `ReferenceError: primordials is not defined`.

```sh
$ node
Welcome to Node.js v12.0.0.
Type ".help" for more information.
> const { NodeVM } = require('vm2');
undefined
> const vm = new NodeVM({ require: { builtin: ['events'] } });
undefined
> vm.run(`require('events')`);
Thrown:
ReferenceError: primordials is not defined
```

**Comment by kimamula** [comment]
Commenting out these lines fixed my issue though I'm not sure it's OK for every use case.
https://github.com/patriksimek/vm2/blob/7f42f09517a99153e6698d5dc7d29d8a287783ab/lib/sandbox.js#L166-L185

**Comment by patriksimek** [comment]
Thanks! Fix released in 3.8.1.

**Comment by kailashyogeshwar85** [comment]
It doesn't work if context: 'sandbox' ?
```
const vm = new NodeVM({
      console: 'inherit',
      sandbox: {
        projectPath
      },
      root: projectPath,
      require: {
        context: 'sandbox',
        external: WHITE_LIST_MODULES,
        builtin: ['assert', 'punycode', 'util', 'querystring', 'event', 'events', 'buffer', 'crypto', 'http', 'https', 'url', 'zlib', 'path', 'stream'],
        mock: {
          net: { },
          os: { },          
          child_process: { },
          fs: { readFileSync: () => "Nice" }
        }
      }
    });
```

**Comment by XmiliaH** [comment]
If you get `Error: Cannot find module 'internal/util/inspect'` see https://github.com/patriksimek/vm2/issues/216. If not, please open a new issue with more details.
