### ISSUE TITLE
Proxy Error on loading module in relative modules

### ISSUE THREAD

**Issue by kailashyogeshwar85** [patriksimek/vm2#223]
```
const vm = new NodeVM({
      console: 'inherit',
      sandbox: {
        modulePath: "abc"
      },
      require: {
        context: 'sandbox',
        external: ['request'],
        builtin: ['assert', 'punycode', 'util', 'querystring', 'event', 'buffer', 'crypto', 'http', 'https', 'url', 'zlib', 'path', 'net', 'stream'],
        mock: {
        }
      }
    });
```

Below is the stack trace
Error in vm  TypeError: 'set' on proxy: trap returned falsish for property '_write'
    at /tmp/cli-87c134f4-56b1-44bd-b49d-973986bc13b1-bl-1505901f-9b2b-4c06-a8c3-c1390fa2399f/node_modules/sshpk/lib/ed-compat.js:27:27
    at Object.EXTENSIONS.(anonymous function) [as .js] (/home/runner/projects/irepo/integration-cli/node_modules/vm2/lib/sandbox.js:83:5)
    at _require (/home/runner/projects/irepo/integration-cli/node_modules/vm2/lib/sandbox.js:321:24)
    at /tmp/cli-87c134f4-56b1-44bd-b49d-973986bc13b1-bl-1505901f-9b2b-4c06-a8c3-c1390fa2399f/node_modules/sshpk/lib/private-key.js:17:16
    at Object.EXTENSIONS.(anonymous function) [as .js] (/home/runner/projects/irepo/integration-cli/node_modules/vm2/lib/sandbox.js:83:5)
    at _require (/home/runner/projects/irepo/integration-cli/node_modules/vm2/lib/sandbox.js:321:24)
    at /tmp/cli-87c134f4-56b1-44bd-b49d-973986bc13b1-bl-1505901f-9b2b-4c06-a8c3-c1390fa2399f/node_modules/sshpk/lib/fingerprint.js:11:18
    at Object.EXTENSIONS.(anonymous function) [as .js] (/home/runer/projects/irepo/integration-cli/node_modules/vm2/lib/sandbox.js:83:5)
    at _require (/home/runner/projects/irepo/integration-cli/node_modules/vm2/lib/sandbox.js:321:24)
    at /tmp/cli-87c134f4-56b1-44bd-b49d-973986bc13b1-bl-1505901f-9b2b-4c06-a8c3-c1390fa2399f/node_modules/sshpk/lib/key.js:8:19

```
// lib/index.js
```
var request = require('request')
module.exports = { fetch: request }

```

**Comment by pradeep-mishra** [comment]
Having the same problem
