### ISSUE TITLE
Cannot find module '../lib/wildcard'

### ISSUE THREAD

**Issue by Schwefelhexa** [patriksimek/vm2#260]
When instantiating a new `NodeVM`, I get the following error:
```
Uncaught Error: Cannot find module '../lib/wildcard'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/renderer_init.js:925:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at Object.require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (D:\Projects\Visual Studio Code\glass-yeti\.webpack\renderer\any_folder/../native_modules/sandbox.js:9:22)
    at new NodeVM (http://localhost:3000/main_window/index.js:41676:19)
    at Function../src/loaders/widget_loader.ts.WidgetLoader.instantiateWidget (http://localhost:3000/main_window/index.js:51804:18)
```

I am using electron-forge 6.0.0 with webpack and typescript support.
The code is run from the renderer context, but the same issue arises in the main process.

I'm fairly new to NodeJS and Electron, so please go easy on me :D

**Comment by tuchk4** [comment]
Same issue when running vm2 on now.sh

**Comment by hharnisc** [comment]
Used version 3.7.0 (before widcard was implemented) and it works. Latest versions appear to be missing the `./lib/wildcard` file
