### ISSUE TITLE
maybePromise._target is not a function

### ISSUE THREAD

**Issue by capaj** [patriksimek/vm2#262]
I am running some async functions and I get these errors:
```
  'TypeError: maybePromise._target is not a function',
  '    at PromiseArray._iterate (/home/capaj/work-repos/looop/project-alpha/node_modules/bluebird/js/release/promise_array.js:93:41)',
  '    at PromiseArray.init [as _init] (/home/capaj/work-repos/looop/project-alpha/node_modules/bluebird/js/release/promise_array.js:79:10)',
  '    at new PromiseArray (/home/capaj/work-repos/looop/project-alpha/node_modules/bluebird/js/release/promise_array.js:25:10)',
  '    at Function.Promise.all (/home/capaj/work-repos/looop/project-alpha/node_modules/bluebird/js/release/promise.js:218:12)',
  '    at batchedIterationInner (/home/capaj/work-repos/looop/project-alpha/back-end/src/util/batchedIteration.ts:34:41)'

```

any way to fix this?

**Comment by capaj** [comment]
oh this was caused by bluebird. It runs fine once I removed it. Closing
