### ISSUE TITLE
Loading modules by relative path does not work with VMScript

### ISSUE THREAD

**Issue by kalevalp** [patriksimek/vm2#288]
This is a new bug introduced in version 3.9.0

When sandboxed code requires a module, the module path is relative to the host execution, not the  script path passed to `vm.run()`.

The following example demonstrates the problem:

    // wrap.js
    const {NodeVM,VMScript} = require("vm2");    
    
    const filePath = 'src/a.js';
    const code     = "const b = require('./b')";
    const script   = new VMScript(code);
    
    let executionEnv = {
        require: {
            context: 'sandbox',
            external: true,
            builtin: ['*'],
        },
    };
    
    const vm = new NodeVM(executionEnv);
    
    vm.run(code, filePath);
    vm.run(script, filePath);

The directory structure for the example is:
    
    .
    └── src
        ├── a.js
        ├── b.js
        └── wrap.js
    
When running the code above from the root directory (i.e., running `node src/wrap.js`) in version 3.9.0 or later, the call `vm.run(code, filePath);` runs successfully, but the call `vm.run(script, filePath);` fails to load the module `b.js`, producing the following error:

     
     /home/kalevalp/tmp/vm-load/node_modules/vm2/lib/main.js:1125
     			throw this._internal.Decontextify.value(e);
     			^
     VMError: Cannot find module './b'
         at _require (/home/kalevalp/tmp/vm-load/node_modules/vm2/lib/sandbox.js:368:25)
         at Object.<anonymous> (vm.js:1:73)
         at NodeVM.run (/home/kalevalp/tmp/vm-load/node_modules/vm2/lib/main.js:1121:29)
         at Object.<anonymous> (/home/kalevalp/tmp/vm-load/src/wrap.js:21:4)
         at Module._compile (internal/modules/cjs/loader.js:778:30)
         at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
         at Module.load (internal/modules/cjs/loader.js:653:32)
         at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
         at Function.Module._load (internal/modules/cjs/loader.js:585:3)
         at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by XmiliaH** [comment]
The filename + path is taken from the VMScript now.
If you change
```JS
const script   = new VMScript(code);
```
to
```JS
const script   = new VMScript(code, {filename: filePath});
```
it should work.

It might be an idea to override the filename from the script if it is given in the run method, however error messages will still use the name given in for the VMScript.

**Comment by kalevalp** [comment]
Thanks!

It's worth updating the readme to reflect these changes.

**Comment by XmiliaH** [comment]
Thanks, will do that.
