### ISSUE TITLE
Printing sandboxed class fails

### ISSUE THREAD

**Issue by XmiliaH** [patriksimek/vm2#295]
Printing a sandboxed class results in an node assert failure.
Tested with v12.16.1.

```JS
console.log(new VM().run('class A {}; A'));
```
will result in
```
internal/assert.js:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (internal/assert.js:14:11)
    at getKeys (internal/util/inspect.js:599:7)
    at formatRaw (internal/util/inspect.js:828:12)
    at formatValue (internal/util/inspect.js:721:10)
    at inspect (internal/util/inspect.js:264:10)
    at formatWithOptions (internal/util/inspect.js:1865:40)
    at Object.Console.<computed> (internal/console/constructor.js:281:10)
    at Object.log (internal/console/constructor.js:291:61)
    at Object.<anonymous> (C:\Users\Nils\Documents\GitHub\vm2\test.js:3:9)
    at Module._compile (internal/modules/cjs/loader.js:1158:30) {
  code: 'ERR_INTERNAL_ASSERTION'
}
```

**Comment by takayama-lily** [comment]
```js
console.log(new VM().run('function A(){};Object.freeze(A)'))
```
This gets the same result
