### ISSUE TITLE
Maximum Call Stack Size Exceeded error

### ISSUE THREAD

**Issue by J-Cake** [patriksimek/vm2#326]
I have no idea where this error comes from, other than that it's internal; Here's the stacktrace:

```
RangeError [Error]: Maximum call stack size exceeded
    at Object.Contextify.value (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:878:20)
    at Object.base.get (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:598:21)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:228:34)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:620:32)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:228:34)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:620:32)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:228:34)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:620:32)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:228:34)
    at Object.base.apply (/home/jcake/Code/Project/Lotus/Launcher/node_modules/.pnpm/vm2@3.9.2/node_modules/vm2/lib/contextify.js:620:32)
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".
```
I feared it may be a circular dependency issue, but after noticing that I've left several of them in and the program still ran suggests it isn't related. Otherwise, I'm not sure what the issue could be.

**Comment by techar** [comment]
You're probably missing, mixing, nesting await/asyncs.... Try your code outside of vm2 first.
