### ISSUE TITLE
can `require('events')` work if context: 'sandbox' ?

### ISSUE THREAD

**Issue by AminHuang** [patriksimek/vm2#333]
node: 14.15.3
vm2: 3.9.2

index.js
```
const {NodeVM} = require('vm2');
const vm = new NodeVM({
    require: {
        context: 'sandbox',
        builtin: ['events'],
    }
});

vm.run(`
    require('events')
`, 'vm.js');
```

node index.js 
```
/Users/jm/vs_prj/ts-vm2/node_modules/vm2/lib/main.js:1125
			throw this._internal.Decontextify.value(e);
			^
VMError [Error]: Error loading 'events'
    at _requireBuiltin (/Users/huangjiamin/vs_prj/ts-vm2/node_modules/vm2/lib/sandbox.js:225:11)
    at _require (/Users/huangjiamin/vs_prj/ts-vm2/node_modules/vm2/lib/sandbox.js:291:12)
    at Object.<anonymous> (vm.js:2:5)
    at NodeVM.run (/Users/huangjiamin/vs_prj/ts-vm2/node_modules/vm2/lib/main.js:1121:29)
    at Object.<anonymous> (/Users/huangjiamin/vs_prj/ts-vm2/index2.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: undefined
}
```

and I found this
```
TypeError [Error]: SymbolFor is not a function
    at events.vm.js:49:20
```

**Comment by MaxGenash** [comment]
@AminHuang it's a known issue: https://github.com/patriksimek/vm2/issues/216#issuecomment-528866482
As a workaround, you can just pass a custom implementation to vm2 replacing the 'events' module.
This worked for me:

_package.json:_
```
    "jsEvents": "npm:events@^3.2.0",
```

ur-code.js:
```
    const jsEvents = require('jsEvents');

    const vm = new NodeVM({
        // ...
        require: {
            builtin: ['*'],
            mock: {
                events: jsEvents,
            }
        },
    });
```

**Comment by ayZagen** [comment]
hey @XmiliaH This issue should be reopened.

**Comment by XmiliaH** [comment]
This seems like a duplicate from https://github.com/patriksimek/vm2/issues/216#issuecomment-528866482 which is still open.
