### ISSUE TITLE
functions running inside the VM don't have access to its scope

### ISSUE THREAD

**Issue by abiank** [patriksimek/vm2#334]
`$ cat vm2test.js
const { VM } = require('vm2');

var TestFunc = function () {console.log(globalVar)}

var vmsandbox = {
    console: console,
    globalVar: 42,
    TestFunc: TestFunc
    }

const vm = new VM({
    timeout: 999,
    sandbox: vmsandbox,
    eval: false
  });

var x = vm.run("console.log(TestFunc())")

$ node vm2test.js
/home/ale/node_modules/vm2/lib/main.js:297
			throw this._internal.Decontextify.value(e);
			^

ReferenceError: globalVar is not defined
    at TestFunc (/home/ale/test/vm2test.js:3:41)
    at Object.base.apply (/home/ale/node_modules/vm2/lib/contextify.js:525:32)
    at vm.js:1:13
    at Script.runInContext (vm.js:130:18)
    at VM.run (/home/ale/node_modules/vm2/lib/main.js:291:64)
    at Object.<anonymous> (/home/ale/test/vm2test.js:17:12)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)

$ node -v
v15.0.1
`

**Comment by abiank** [comment]
FYI for anybody also having this issue: i was able to solve it by defining the function inside the VM.

**Comment by XmiliaH** [comment]
This is to be expected, since functions in JS are closures and the variables are bound when the closure is created.
