### ISSUE TITLE
Bound function causes TypeError: 'ownKeys' on proxy: trap result did not include 'prototype'

### ISSUE THREAD

**Issue by xnv** [patriksimek/vm2#345]
Hi,

I found that `console.log()` for the bound functions causes a `TypeError`.

```javascript
(new NodeVM().run('console.log((function () {}).bind(null))'))
```

prints:

```text
Uncaught TypeError: 'ownKeys' on proxy: trap result did not include 'prototype'
    at getOwnPropertySymbols (<anonymous>)
    at getKeys (internal/util/inspect.js:671:19)
    at formatRaw (internal/util/inspect.js:919:12)
    at formatValue (internal/util/inspect.js:812:10)
    at inspect (internal/util/inspect.js:337:10)
    at formatWithOptionsInternal (internal/util/inspect.js:2016:40)
    at formatWithOptions (internal/util/inspect.js:1898:10)
    at console.value (internal/console/constructor.js:323:14)
    at console.log (internal/console/constructor.js:358:61)
    at Object.base.apply (.../vm2/lib/contextify.js:621:32)
```

Confirmed with `vm2@3.9.3` on Node.js v14.16.1.

**Comment by xnv** [comment]
As the error says, this seems to be a problem around `ownKeys()` and the `prototype` property. Actually this is not specific for `console.log()`. The similar problem seems reproducible with `Reflect.ownKeys()`, `util.inspect()` and so on.

Here are some observations I have:

1. [The spec][ownkeys-proxy] says that the result of `ownKeys()` trap on `Proxy` must include all non-configurable keys found in proxy target.
2. Ordinary (non-arrow) functions always have `prototype` as a non-configurable property but bound functions not (unless explicitly assigned).
3. When decontextifying a (non-arrow) function, vm2 uses an anonymous (non-arrow) function as the actual proxy target instead of the given function (ref. [createBaseObject()][create-base-obj]).
4. vm2 [explicitly assigns `null` to `prototype`][set-proto] of this anonymous function but of course the the property sill exists.

This causes the actual proxy target always have an `prototype` property for functions and then `"prototype"` must be included in the results of the `ownKeys()` trap.

But [the current implementation][ownkeys-impl] returns the keys found in the original function (not the actual proxy target). When the function is bound one, this does not include `"prototype"`. So the error occurs: 'ownKeys' trap result did not include 'prototype'.

Unfortunately, AFAIK it is not possible to determine whether a function is bound or not. But at least, I think the acutal proxy target should be bound (to omit the `prototype`) if the target function lacks the property.

[ownkeys-proxy]: https://tc39.es/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-ownpropertykeys
[create-base-obj]: https://github.com/patriksimek/vm2/blob/d12bdbdb647ba14d7b788ea6b2089df9c09028df/lib/contextify.js#L69-L83
[set-proto]: https://github.com/patriksimek/vm2/blob/d12bdbdb647ba14d7b788ea6b2089df9c09028df/lib/contextify.js#L80
[ownkeys-impl]: https://github.com/patriksimek/vm2/blob/d12bdbdb647ba14d7b788ea6b2089df9c09028df/lib/contextify.js#L430-L432

**Comment by XmiliaH** [comment]
Thanks for the report. Should be fixed in the master branch.
