### ISSUE TITLE
Lodash/fp Loading Fails Within a Sandbox 

### ISSUE THREAD

**Issue by kudla** [patriksimek/vm2#365]
Hi.
I'm trying to sandbox over `NodeVM` a module which itself imports `lodash/fp` 
And it fails loading `lodash`
```
TypeError [Error]: 'set' on proxy: trap returned falsish for property 'convert'
    at /project/node_modules/lodash/fp/_baseConvert.js:546:20
    at r (/project/node_modules/lodash/lodash.min.js:9:347)
    at _f (/project/node_modules/lodash/lodash.min.js:84:352)
    at baseConvert (/project/node_modules/lodash/fp/_baseConvert.js:537:3)
    at /project/node_modules/lodash/fp.js:2:46
    at Object.EXTENSIONS.<computed> [as .js] (/project/node_modules/vm2/lib/sandbox.js:91:5)
    at _require (/project/node_modules/vm2/lib/sandbox.js:406:24)
    at /project/src/lib/loadBalancing/LoadCounter/LoadCounter.ts:2:1
    at Object.EXTENSIONS.<computed> [as .ts] (/project/node_modules/vm2/lib/sandbox.js:91:5)
    at _require (/project/node_modules/vm2/lib/sandbox.js:406:24)
```

on a code like this
```js
  each(keys(_), function(key) {
    var func = _[key];
    if (typeof func == 'function') {
      var length = pairs.length;
      while (length--) {
        if (pairs[length][0] == key) {
          return;
        }
      }


     // over this assignment
      func.convert = createConverter(key, func);
      pairs.push([key, func]);
    }
  });
```

`NodeVM` config looks like this
```js
{
            console: 'inherit',
            sandbox: {
                Date: {now: () => 33}
            },
            sourceExtensions: ['js', 'ts'],
            compiler: tsTranspile,
            require: {
                resolve: (moduleName: string, basedir: string) => {
                    return moduleName
                },
                external: ['*'],
                builtin: ['*'],
                context: 'sandbox',

            }
  };
```

Pease is it possible to bypass some modules at all?
Or what would be the solution for the issue?

**Comment by savokiss** [comment]
What's the detail of `tsTranspile`? I've used `require.context = 'host'` for most of the npm modules.

**Comment by XmiliaH** [comment]
This is intended. This happens since `lodash` tries to add a property to the read-only `Buffer.isBuffer` method.
As a workaround you could use:
```js
const oldBuffer = Buffer;
Buffer = undefined;
const fp = require("lodash/fp");
Buffer = oldBuffer;
```
