### ISSUE TITLE
3.9.4 breakchange? 

### ISSUE THREAD

**Issue by ACERY1** [patriksimek/vm2#371]
My Code:
```
const { VM } = require('vm2');
new VM();
```

TypeError: Cannot set property 'value' of undefined
      at setupCallSite (node_modules/_vm2@3.9.4@vm2/lib/contextify.js:1087:19)
      at Object.<anonymous> (node_modules/_vm2@3.9.4@vm2/lib/contextify.js:1090:4)
      at new VM (node_modules/_vm2@3.9.4@vm2/lib/main.js:722:88)

![image](https://user-images.githubusercontent.com/19555547/137106598-3f5f869e-144d-442e-8c06-bac74ecaacea.png)

what may cause this error ?

**Comment by XmiliaH** [comment]
Should be fixed in the master branch
