### ISSUE TITLE
spawnSync return EINVAL Error

### ISSUE THREAD

**Issue by lvqq** [patriksimek/vm2#383]
- vm2: 3.9.3
- nodejs: 12.16.1

When I use spawnSync in vm2, I get an Error which message is **spawnSync echo EINVAL**, but it works fine without vm2. Is there any difference between vm2 context and node context? And how can I get right output when using spawnSync in vm2? 

Here is my code:
```javascript
const { NodeVM } = require('vm2')
const vm = new NodeVM({
  require: {
    external: true,
    builtin: [
      'child_process',
    ],
  },
});
const code = `
const spawnSync = require('child_process').spawnSync;
  module.exports = () => {
    const data = spawnSync('echo', ['test']);
    console.log(data)
  }
`
const fn = vm.run(code, 'vm.js')
fn()
```

Then I get:
```
{
  error: Error: spawnSync echo EINVAL
      at Object.spawnSync (internal/child_process.js:1041:20)
      at spawnSync (child_process.js:616:24)
      at Object.base.apply (/node_modules/vm2/lib/contextify.js:621:32)
      at module.exports (vm.js:4:18)
      at Object.base.apply (/node_modules/vm2/lib/contextify.js:228:34)
      at Object.<anonymous> 
      at Module._compile (internal/modules/cjs/loader.js:1158:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
    errno: 'EINVAL',
    code: 'EINVAL',
    syscall: 'spawnSync echo',
    path: 'echo',
    spawnargs: [ 'test' ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

By the way, it meets my expectation in vm:
```javascript
const vm = require('vm');
const code = `
const spawnSync = require('child_process').spawnSync;
  module.exports = () => {
    const data = spawnSync('echo', ['test']);
    console.log(data)
  }
`
const fn = vm.runInNewContext(code, {
  require,
  module,
  console
});
fn()

// output
//  {
//    status: 0,
//    signal: null,
//    output: [ null, <Buffer 74 65 73 74 0a>, <Buffer > ],
//    pid: 44301,
//    stdout: <Buffer 74 65 73 74 0a>,
//    stderr: <Buffer >
//  }
```

**Comment by XmiliaH** [comment]
This is caused by node since `spawnSync` seems to not accept Proxies as the second argument. This cannot be fixed from our side. It would be best to just write a secure wrapper in the host around `spawnSync` which creates a new array.
