### ISSUE TITLE
`3.9.5` -> `3.9.7` `Unexpected token` error

### ISSUE THREAD

**Issue by BenBirt** [patriksimek/vm2#406]
When I try to bump (https://github.com/dataform-co/dataform/pull/1315) our repo's `vm2` version, just about all of our unit tests fail in the same way:

```
        at Parser.pp$4.raise (node_modules/vm2/node_modules/acorn/dist/acorn.js:3460:15)
        at Parser.pp$9.unexpected (node_modules/vm2/node_modules/acorn/dist/acorn.js:756:10)
        at Parser.pp$9.semicolon (node_modules/vm2/node_modules/acorn/dist/acorn.js:733:68)
        at Parser.pp$8.parseExpressionStatement (node_modules/vm2/node_modules/acorn/dist/acorn.js:1216:10)
        at Parser.pp$8.parseStatement (node_modules/vm2/node_modules/acorn/dist/acorn.js:949:26)
        at Parser.pp$8.parseBlock (node_modules/vm2/node_modules/acorn/dist/acorn.js:1232:23)
        at Parser.pp$8.parseStatement (node_modules/vm2/node_modules/acorn/dist/acorn.js:914:38)
        at Parser.pp$8.parseTopLevel (node_modules/vm2/node_modules/acorn/dist/acorn.js:813:23)
        at Parser.parse (node_modules/vm2/node_modules/acorn/dist/acorn.js:586:17)
        at Function.parse (node_modules/vm2/node_modules/acorn/dist/acorn.js:636:37)
```

**Comment by XmiliaH** [comment]
Could you supply an example test case for which this happens.

**Comment by BenBirt** [comment]
Sure, clone https://github.com/dataform-co/dataform, and run `bazel test tests/api:examples.spec`.

**Comment by XmiliaH** [comment]
Thanks, found the problem. `findBestExtensionHandler` did not include the dot. Therefore always using the `.js` extension handler. This resulted in the parser error for `.json` files.

**Comment by XmiliaH** [comment]
This should be fixed in version 3.9.8

**Comment by BenBirt** [comment]
Thanks! 👍

**Comment by BenBirt** [comment]
(merged in https://github.com/dataform-co/dataform/pull/1315)
