### ISSUE TITLE
EVAL breaks in NodeVM from 3.9.4

### ISSUE THREAD

**Issue by VeNoMouS** [patriksimek/vm2#415]
```javascript
const vm2 = require('vm2');

const vm = new vm2.NodeVM();
vm.run(`
    let test = true;
    eval('0, test')    
`);
```

```
/tmp/node_modules/vm2/lib/bridge.js:481
                                throw thisFromOtherForThrow(e);
                                ^
ReferenceError [Error]: test is not defined
    at eval (eval at apply (/tmp/node_modules/vm2/lib/setup-sandbox.js:371:10), <anonymous>:1:1)
    at eval (<anonymous>)
    at Object.apply (/tmp/node_modules/vm2/lib/setup-sandbox.js:371:10)
    at vm.js:3:5
    at BaseHandler.apply (/tmp/node_modules/vm2/lib/bridge.js:479:11)
    at NodeVM.run (/tmp/node_modules/vm2/lib/nodevm.js:425:23)
    at Object.<anonymous> (/tmp/test.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

tested with 3.9.9 all the way down to 3.9.0...  starts breaking from 3.9.4

# Edit...

Works under `vm2.VM()` in 3.9.9 fwiw...

**Comment by XmiliaH** [comment]
This is a known issue https://github.com/patriksimek/vm2#known-issues and cannot be fixed.
