### ISSUE TITLE
Cannot load dynamic import with relative path

### ISSUE THREAD

**Issue by flyon** [patriksimek/vm2#434]
code being executed in VMNode

```
export var loadData = () => JSONLD.parsePromise(import('../data/schema.json'));
```

**Error: `Cannot find module '../data/schema.json'`**

Setup
```
let vm = new NodeVM({
  eval: true,
  sandbox: {},
  require: {
    external: true,
    builtin:['crypto','https'],
  },
});

vm.run(`module.exports = require("${npmPath}");`,relativeFilePath);
```

The filepath is correct, but possibly it's not resolving because the context = host? 
Changing context to sandbox causes many new errors though, see below.

How does one do dynamic imports with relative paths?

```
//error with content: 'sandbox':
 Failed to execute script. TypeError [Error]: 'set' on proxy: trap returned falsish for property 'fil
ename'
    at C:\web\lincd\node_modules\esm\esm.js:1:967
    at BaseHandler.apply (C:\web\lincd\lincd.org\node_modules\vm2\lib\bridge.js:479:11)
    at NodeVM.run (C:\web\lincd\lincd.org\node_modules\vm2\lib\nodevm.js:425:23)
    at LegacyResolver.loadJS (C:\web\lincd\lincd.org\node_modules\vm2\lib\resolver-compat.js:119:7) 
    at loadJS (C:\web\lincd\lincd.org\node_modules\vm2\lib\nodevm.js:248:46)
    at BaseHandler.apply (C:\web\lincd\lincd.org\node_modules\vm2\lib/bridge.js:479:11)
    at Module._extensions.<computed> (C:\web\lincd\lincd.org\node_modules\vm2\lib/setup-node-sandbox.js:144:48)
    at requireImpl (C:\web\lincd\lincd.org\node_modules\vm2\lib/setup-node-sandbox.js:117:3)        
     at require (C:\web\lincd\lincd.org\node_modules\vm2\lib/setup-node-sandbox.js:165:10)
     at C:\web\lincd\node_modules\@digitalbazaar\http-client\index.js:7:11
```

**Comment by XmiliaH** [comment]
Without `require.context='sandbox'` the module loaded by `require("${npmPath}");` is in the host context. However, even when `require.context='sandbox'` this will not work as vm2 does currently not support JS Modules including dynamic imports.

**Comment by flyon** [comment]
Thanks for the clarification
