### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by xiaokanghub** [patriksimek/vm2#435]
Hi, developer
I got the error when i run example code, i don't know how to solve it
# env
macos: 10.14.6
Visual Studio Code: 1.66.2
nodejs: v15.14.0
# code
```
const {VM} = require('vm2');
new VM().run('this.constructor.constructor("return process")().exit()');
```
# issue
some info like this
```
Uncaught Object Proxy
    at runScript (/Users/xkang/AndroidTools/RE_Project/kugou/node_modules/vm2/lib/vm.js:287:5)
    at run (/Users/xkang/AndroidTools/RE_Project/kugou/node_modules/vm2/lib/vm.js:503:16)
    at <anonymous> (/Users/xkang/AndroidTools/RE_Project/kugou/kugou_js/index.js:8:10)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Module._load (node:internal/modules/cjs/loader:813:14)
    at executeUserEntryPoint (node:internal/modules/run_main:76:12)
    at <anonymous> (node:internal/main/run_main_module:17:47)
No debugger available, can not send 'variables'
```

**Comment by XmiliaH** [comment]
The code is expected to throw an exception as `process` is not defined. What did you expect to get instead?

**Comment by xiaokanghub** [comment]
> The code is expected to throw an exception as `process` is not defined. What did you expect to get instead?

I expect to get an exception as process is not defined, but get Uncaught Object Proxy

**Comment by XmiliaH** [comment]
Sorry, I cannot reproduce the issue. When I run this code in v3.9.9 I get:
```
/app/lib/vm.js:287
                                throw bridge.from(e);
                                ^
ReferenceError [Error]: process is not defined
    at anonymous (eval at makeFunction (/app/lib/setup-sandbox.js:348:9), <anonymous>:3:1)
    at vm.js:1:47
    at Script.runInContext (node:vm:141:12)
    at VM.runScript (/app/lib/vm.js:285:18)
    at VM.run (/app/lib/vm.js:503:16)
    at Object.<anonymous> (/app/test.js:2:10)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

**Comment by XmiliaH** [comment]
It seems that this happens when running the script with the vscode run command. I have no idea how vscode generates the error message and if there is something we can do, since the error vscode will get is actually a Proxy.

**Comment by xiaokanghub** [comment]
> It seems that this happens when running the script with the vscode run command. I have no idea how vscode generates the error message and if there is something we can do, since the error vscode will get is actually a Proxy.

kk, thanks
