### ISSUE TITLE
Unable to require local files in parent directory

### ISSUE THREAD

**Issue by clample** [patriksimek/vm2#452]
Hello and thank you for this excellent library!

I would like to run programs consisting of multiple files using vm2. This doesn't work, though, when a file in a parent directory is imported. I created a reproducing example here: https://github.com/clample/vm2-test. 

In this example, the VM2 setup is contained in [index.js](https://github.com/clample/vm2-test/blob/main/index.js).  The `NodeVM` is configured with:
```
const vm = new NodeVM({
  console: 'inherit',
  wrapper: 'commonjs',  
  require: {
    root: ['dir1'],
    external: [],
    context: 'sandbox'
  },
});
```

The files to be run inside the VM are:

```
.
└── dir1
    ├── dir2
    │   └── intermediate.js
    ├── intermediate.js
    └── value.js
```

Executing the repo with `npm install && npm start` gives:

```
% npm install && npm start

> vm2-parent-resolve-issue@1.0.0 start /Users/clample/projects/vm2-parent-resolve-issue
> node index.js

Running from dir1
It works true
Running from dir1/dir2
/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/bridge.js:487
				throw thisFromOtherForThrow(e);
				^

VMError: Cannot find module '../value'
    at LegacyResolver.resolveFull (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/resolver.js:279:10)
    at LegacyResolver.resolveFull (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/resolver-compat.js:100:17)
    at LegacyResolver.resolve (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/resolver.js:105:15)
    at VM2 Wrapper.apply (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at /Users/clample/projects/vm2-parent-resolve-issue/dir1/dir2/intermediate.js:1:94
    at VM2 Wrapper.apply (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/bridge.js:485:11)
    at NodeVM.run (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/nodevm.js:425:23)
    at LegacyResolver.loadJS (/Users/clample/projects/vm2-parent-resolve-issue/node_modules/vm2/lib/resolver-compat.js:119:7) {
  code: 'ENOTFOUND'
}
```

In this case, the file `dir1/intermediate.js` is able to require `dir1/value.js`, but the file `dir1/dir2/intermediate.js` fails to require `dir1/value.js`. I would expect both cases to be permissible because the `NodeVM` is configured with `require.root: ['dir1']`.

The example passes if `require.context: sandbox` is removed. In my case, though, I would like for all of the files in `dir1` should be sandboxed.

From debugging this, it looks like import is being rejected here:

https://github.com/patriksimek/vm2/blob/6fcb7079c2a7673f3682f590df07417b1f4991fe/lib/resolver-compat.js#L61-L71

Do you have any guidance on how I could get this working?

**Comment by XmiliaH** [comment]
Can you try with:
```js
const vm = new NodeVM({
  console: 'inherit',
  wrapper: 'commonjs',  
  require: {
    root: ['dir1'],
    external: true,
    context: 'sandbox'
  },
});
```
External should be true if you want to allow modules to be able to require any file under the root directories.

**Comment by clample** [comment]
@XmiliaH thank you so much for taking a look at this. It works with `external: true`  🎉

**Comment by renatoargh** [comment]
Hey @XmiliaH thanks for the great work! 

I have a question; how can I enable submodule importing (as you explained with `external: true`) but at the same time be able to whitelist external modules (as we do when we specify a string array on `require.module`?

**Comment by XmiliaH** [comment]
There is no `require.module`. I interpret the question that there is a module tree like:
```
main/
├── main.js
└── node_modules/
    └── outermodule/
        ├── index.js
        └── node_modules/
            └── innermodule/
                └── index.js
```
In this case main requires outermodule which requires innermodule.
This would either require the `require.external` to be `["outermodule","innermodule"]` or when inner modules are not known `["outermodule","outermodule/**"]`.
