### ISSUE TITLE
how require file from memfs in vm2?

### ISSUE THREAD

**Issue by i5ting** [patriksimek/vm2#472]
use require.customRequire code here:

```

const { NodeVM } = require('vm2');
const { fs, vol } = require('memfs');
const { patchRequire } = require('fs-monkey');

vol.writeFileSync('/index2.js', 'console.log("hi world")');
vol.writeFileSync('/index.js', `require('/index2');console.log("hi world")`);

patchRequire(vol); // new require


const vm = new NodeVM({
    require: {
        external: true,
        root: process.cwd(),
        customRequire: require
    }
});


vm.run(`
    require('/index'); 
`, 'test-with-memfs.js');

```

error

```
/Users/i5ting/workspace/github/test/node_modules/vm2/lib/bridge.js:487
				throw thisFromOtherForThrow(e);
				^

VMError: Cannot find module '/index'
    at DefaultResolver.resolveFull (/Users/i5ting/workspace/github/test/node_modules/vm2/lib/resolver.js:251:10)
    at DefaultResolver.resolve (/Users/i5ting/workspace/github/test/node_modules/vm2/lib/resolver.js:105:15)
    at VM2 Wrapper.apply (/Users/i5ting/workspace/github/test/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/Users/i5ting/workspace/github/test/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/Users/i5ting/workspace/github/test/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at test-with-memfs.js:2:5
    at VM2 Wrapper.apply (/Users/i5ting/workspace/github/test/node_modules/vm2/lib/bridge.js:485:11)
    at NodeVM.run (/Users/i5ting/workspace/github/test/node_modules/vm2/lib/nodevm.js:426:23)
    at Object.<anonymous> (/Users/i5ting/workspace/github/test/vm2.js:22:4)
    at Module._compile (node:internal/modules/cjs/loader:1095:14) {
  code: 'ENOTFOUND'
}
```

**Comment by XmiliaH** [comment]
This is currently not supported. The `customRequire` is not used for resolving the files but the filesystem is currently used.

**Comment by i5ting** [comment]
> This is currently not supported. The `customRequire` is not used for resolving the files but the filesystem is currently used.

use unionfs maybe a good choice

**Comment by i5ting** [comment]
<img width="1440" alt="截屏2022-09-21 23 16 34" src="https://user-images.githubusercontent.com/3118295/191543495-55a5815e-f739-436a-82a7-fd7cc11f307c.png">

**Comment by elglogins** [comment]
@i5ting did  you succeed with this?
