### ISSUE TITLE
Error: Invalid node type 'ObjectPattern' expected 'Identifier' error

### ISSUE THREAD

**Issue by ppedziwiatr** [patriksimek/vm2#485]
Hey,

I'm getting 
```
Error: Invalid node type 'ObjectPattern' expected 'Identifier'
    at assertType (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/vm2/lib/transformer.js:9:32)
    at /Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/vm2/lib/transformer.js:115:18
    at c (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:81:9)
    at Object.base.TryStatement (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:246:25)
    at c (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:79:24)
    at Object.skipThrough (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:186:39)
    at c (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:79:24)
    at Object.base.Program.base.BlockStatement.base.StaticBlock (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:198:7)
    at c (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:79:24)
    at Object.skipThrough (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/acorn-walk/dist/walk.js:186:39)
```

while trying to load an untrusted script that should be evaluated via VM2.

Question - is there a way to show some more descriptive error - e.g. line number of the original script or at least a "surrounding" of the code that is causing the issue?

The code itself is very complicated and long (https://sonar.warp.cc/#/app/contract/9aetS5_kSsCdDI14y9e1TlL9CF6xjI2sLeZOnMHgwPc#code) , so it's hard to determine what exactly is causing the issue..

**Comment by XmiliaH** [comment]
Thanks for the report,
this happens with
```js
try{}catch({a}){}
```
Need to look into how to fix this.

**Comment by ppedziwiatr** [comment]
Ok, so that's probably the problematic part:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/84311757/203289013-5f3f60b8-15d9-408b-a477-5c7f7a0e2e7d.png">

Thanks for the quick response!

**Comment by XmiliaH** [comment]
Fixed in git head

**Comment by ppedziwiatr** [comment]
That's awesome! Do you know when it will be released?

**Comment by XmiliaH** [comment]
Just did the release
