### ISSUE TITLE
Limit access to built-in modules

### ISSUE THREAD

**Issue by singh-kiran** [patriksimek/vm2#49]
Got excited looking at the ability to have control on limiting a user script from accessing built-in modules. 

The access denial works for only one level, if an user script loads an other module which indeed access built-in module then no checks are done.

Here is a simple example for the scenario that I am talking about:

STEP 1 :: Create a main.js file which executes sampleOne.js in a sandbox.
```javascript
var fs = require('fs')
const {NodeVM} = require('vm2');
const vm = new NodeVM({
    console: 'inherit',
    sandbox: {},
    require: {
        external: true,
        builtin: ['path'],
        root: "./",
        mock: {
        }
    }
});
var scriptContent = fs.readFileSync('./sampleOne.js');
vm.run(scriptContent, 'sampleOne.js');
```

STEP 2 :: Create sampleOne.js file with following content which invokes an other module.
```javascript
var sampleTwo = require('./sampleTwo.js');
var fileName = 'sampleTwo.js';
console.log('SampleOne:: Invoke sampleTwo printFileContent:' + fileName);
sampleTwo.printFileContent(fileName); 
```

STEP 3:: Create sampleTwo.js which will access built-in "fs" module to read a file content.
```javascript
var fs = require('fs');
exports.printFileContent = function(fileName) {
    console.log('SampleTwo:: print content of file: ' + fileName);
    var fileContent = fs.readFileSync(fileName)
    console.log('\n\nfs module is accessible.\n');
}
```

STEP 4:: Execute main.js and in the output we can see that sampleTwo.js file can read its own file content using fs module.
```
ksingh-mac:test ksingh$ node main.js 
SampleOne:: Invoke sampleTwo printFileContent:sampleTwo.js
SampleTwo:: print content of file: sampleTwo.js
fs module is accessible.
```

When I try to access fs module in sampleOne.js, there is a proper error message saying:
```
VMError: Access denied to require 'fs'
    at _require (/Users/ksingh/projects/tekton/nodejs/node_modules/vm2/lib/sandbox.js:178:13)
    at Object.<anonymous> (/Users/ksingh/projects/tekton/nodejs/test/sampleOne.js:1:72)
    at NodeVM.run (/Users/ksingh/projects/tekton/nodejs/node_modules/vm2/lib/main.js:301:27)
    at Object.<anonymous> (/Users/ksingh/projects/tekton/nodejs/test/main.js:17:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
```

Is there any other setting that needs to be done on NodeVM to deny access for built-in modules for nested files.

Note: I am using node v6.2.0.

**Comment by patriksimek** [comment]
You need to configure VM to require submodules inside the sandbox.

```javascript
const vm = new NodeVM({
    console: 'inherit',
    sandbox: {},
    require: {
        context: 'sandbox', // <------
        external: true,
        builtin: ['path'],
        root: "./",
        mock: {
        }
    }
});
```
