### ISSUE TITLE
vm2 can't manage out-defined function

### ISSUE THREAD

**Issue by singchia** [patriksimek/vm2#97]
I found that a vm-out-defined function can't be managed by vm as I limited **http module** can't be global var or be required, like:
``` javascript
const { NodeVM } = require('vm2');
const vm = new NodeVM({
    console: 'inherit',
    sandbox: { hello: hello },
    require: {
        external: false,
        builtin: ['fs', 'path'],
    }
});
var code = `
    hello() 
`;

function hello() {
    var http = require('http')
    var option = {
        host: 'www.baidu.com',
    }
    var req = http.request(option, function(rsp) {
        var data = '';
        rsp.on('data', function(chunk) {
            data += chunk;
        }).on('end', function() {
            console.log('hello');
        })
    });
    req.on('error', function(err) {
        console.log('error');
    })
    req.setTimeout(10000);
    req.write('hei');
    req.end();
}

vm.run(code);
```
output:
hello

but when I define the hello function in vm code:
``` javascript
const { NodeVM } = require('vm2');
const vm = new NodeVM({
    console: 'inherit',
    sandbox: {},
    require: {
        external: false,
        builtin: ['fs', 'path'],
    }
});
var code = `
    hello()  
    function hello() { 
        var http = require('http') 
        var option = { 
            host: 'www.baidu.com', 
        } 
        var req = http.request(option, function(rsp) { 
            var data = ''; 
            rsp.on('data', function(chunk) { 
                data += chunk; 
            }).on('end', function() { 
                console.log('hello'); 
            }) 
        }); 
        req.on('error', function(err) { 
            console.log('error'); 
        }) 
        req.setTimeout(10000); 
        req.write('hei'); 
        req.end(); 
    }
`;
vm.run(code);
```
it works fine: 
```
vm2/lib/main.js:426
                        throw this._internal.Decontextify.value(e);
                        ^
VMError: Access denied to require 'http'
    at _require (/Users/zhaizenghui/Aladdin/deps/nodejsDeps/node_modules/vm2/lib/sandbox.js:183:13)
    at hello (vm.js:4:20)
    at Object.<anonymous> (vm.js:2:5)
    at NodeVM.run (/Users/zhaizenghui/Aladdin/deps/nodejsDeps/node_modules/vm2/lib/main.js:424:27)
    at Object.<anonymous> (/Users/zhaizenghui/Aladdin/src/nodejsSrc/frameServerWithVM/test.js:34:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I've googled a lot but got no answer even close, why is it and any method to avoid or fix it?

details:
[https://gist.github.com/singchia/46b01c8697df0dbe889f87af9921c8f9](url)
[https://gist.github.com/singchia/d36b8f918abbc29b71db84a7f85128a8](url)

**Comment by beltsonata** [comment]
Have you tried
```
context: 'sandbox',
external: true,
builtin: [http]
```
in your `require` object?

You might have `require` http in your code that runs NodeVM too.
